### ISSUE TITLE
张诗颖完成 Py103 入学任务啦

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [OpenMindClub/PythonStartUp#54]
# 作业提交地址
- [exercise 0-17](https://github.com/zhangshiyinrunwithcc/Py103)

# 作业笔记地址
- [exercise 0-17](https://github.com/zhangshiyinrunwithcc/Py103/blob/master/LPYHW_log_ex0-17.md)

**Comment by liangpeili** [comment]
3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6 里，把1/4里的4换成4.0没有变化吗？

**Comment by zhangshiyinrunwithcc** [comment]
@liangpeili 

- 不不不，不是把 `3 + 2 + 1 - 5 + 4 % 2 - 1 / 4 + 6`的`4`换成`4.0`

- 是其他地方的，我没有写清楚

- 回头我翻看一下，具体是哪个exercise里面的，study drill的任务。
